openshift/machine-api-provider-openstack

pkg/apis/openstackproviderconfig/v1alpha1/convert.go, pkg/machine/actuator.go, pkg/machine/utils.go, pkg/utils/utils.go
In CAPO we were adding default tags to VMs and ports. This commit makes
sure MAPO adds them too. I don't think they're useful and the one built
from machine namespace and cluster ID is just weird, but anyway we
should attempt to maintain the API contract.
=> Add OpenShift CAPO default tags

pkg/apis/openstackproviderconfig/v1alpha1/types.go, pkg/machine/convert.go
Seems like these options got added in late CAPO and we haven't copied
them to MAPO. So this commit adds them again.
=> Add Profile and Trunks to Ports and Networks

go.mod, go.sum, vendor/modules.txt
Which is the same commit as before, just more explicit with a tag.
=> Depend on CAPO v0.6.3

pkg/machine/actuator.go, pkg/machine/convert.go
The installer started supporting multiple VIPs for API and ingress in OpenShift 4.12[1].
This commit adds support to use multiple VIPs instead of only one when defining the
allowed-address-pairs in the Servers Ports.
[1] https://github.com/openshift/installer/pull/5798
=> Add dual stack API and Ingress VIPs support

pkg/machine/convert.go, pkg/machine/convert_test.go
Most CAPO structures only accept a ProjectID. Before this change, the TenantID potentially present in the input filters was ignored. With this change, CAPO is passed the input TenantID if ProjectID is empty.
---
In a separate commit, this PR also addresses an inconsistency with subnet ID selection, which is not severe enough to warrant a bug report on its own.
In order to create ports for a machine, conversion functions receive a Subnet object that has two properties potentially holding the subnet identifier: `subnet.UUID` and `subnet.Filter.ID`. Before this patch, they were used inconsistently: in case they were both populated, `subnet.UUID` was passed to CAPO, while `subnet.Filter.ID` was used to find the subnet's network.
With this change, `subnet.UUID` always takes precedence over …
=> OCPBUGS-2153: Use TenantID if ProjectID is empty

pkg/machine/convert.go
Most CAPO structures only accept a ProjectID. Before this change, the TenantID potentially present in the input filters was ignored. With this change, CAPO is passed the input TenantID if ProjectID is empty.
This is a manual cherry-pick of https://github.com/openshift/machine-api-provider-openstack/pull/62
=> OCPBUGS-10607: Use TenantID if ProjectID is empty

Dockerfile.rhel, Makefile
Aligns our Dockerfile with image building best practices by using make to build our binaries. This necessitates a small change to the Makefile itself to align binary names.
Signed-off-by: Stephen Finucane <stephenfin@redhat.com>
=> Rework how we build the container image

go.mod, go.sum, vendor/modules.txt
Upgrade goproxy to prevent CVE-2023-37788.
=> OCPBUGS-16586: Bump goproxy

.gitignore, Makefile, cmd/manager/main.go, hack/version.sh, pkg/clients/machineservice.go, pkg/clients/utils.go, version/version.go
This can be a helpful breadcrumb when debugging services.
> **Note**
> Unlike https://github.com/openshift/openstack-cinder-csi-driver-operator/pull/123 and
> https://github.com/openshift/csi-driver-manila-operator/pull/191, we need to
> create the `version` package here and modify our `Makefile` to configure
> correct version attributes.
=> Configure User Agent

go.mod, go.sum, vendor/modules.txt, vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/services/compute/instance_types.go
Sync CAPO dependency with the content of release-0.7 to include a fix needed for dual-stack installs.
Commands that were run `go mod tidy` and `go mod vendor`.
=> Bump CAPO to match branch release-0.7

cmd/manager/main.go
The Machine controller that we run doesn't set the SyncPeriod. This means that Machine objects are not periodically reconciled with the status of them in OpenStack.
This is a problem when the user adds a floating IP to a Server manually. In such case cloud-provider-openstack will notice it and update the Node object accordingly. This will cause Kubelet to generate a new CSR with updated SANs including new FIP address. Then cluster-machine-approver will compare the list of SANs from the CSR with Machine's Status.Addresses and will never find the FIP failing the approval.
This commit sets SyncPeriod of the controller to 1 hour in order to make sure Machines are periodically reconciled with the state of the instances in OpenStack just like Nodes are.
=> Bug OCPBUGS-4629: Set controller's SyncPeriod to 1 hour

cmd/manager/main.go
This was left over from debugging and should have been removed. Do so now.
Signed-off-by: Stephen Finucane <stephenfin@redhat.com>
=> Remove unnecessary print

pkg/machine/convert.go
Fixing `MachineToInstanceSpec` when there are no security groups in ports.
=> OCPBUGS-22319: fix MachineToInstanceSpec when SG are nil

pkg/machine/convert.go
during conversion to capo v1alpha7, we missed adding the port profile in
the else.
=> OSASINFRA-3283: convert: add missing port profile

pkg/machine/actuator.go, pkg/machine/convert.go, pkg/machine/convert_test.go
We were building a full `InstanceSpec` struct as part of our Delete operation before promptly throwing the bulk of it away as we only needed the root volume information.
This is wasteful as building the `InstanceSpec` involves looking up resources to resolve both identifiers (like `serverGroupName`, which must be resolved to an ID of a new or existing server group using the Compute API) and filters (such as a `networks[*].filter.subnets[*]`, which must be resolved to an ID if a network name is given).
It's also the source of bugs. This is because we currently do not validate or propagate changes to a `Machine` after initial creation meaning a user can update their `Machine` to use e.g. an invalid network name. While this would have no immediate effect - remember, the changes aren't …
=> OCPBUGS-16597: Don't build InstanceSpec during delete operations

pkg/machine/convert.go
With the recent bump of CAPO there is no need to retrieve the ID of the Network anymore to specify it in the Port.
=> OSASINFRA-3297: Remove unnecessary retrieval of Network ID

pkg/machine/actuator.go, pkg/machine/convert.go, pkg/machine/convert_test.go
Before this patch, machines could get stuck in Deleting phase when they didn't have a root volume defined.
=> OCPBUGS-23913: Fix nil pointer exception when deleting machines without a root volume

cmd/manager/main.go
The flag is set to true by default [1] and setting it like we do causes
a panic with go 1.21 [2]. There are also plans to remove the flag entirely
from future versions of k8s [3].
[1] https://github.com/kubernetes/klog/blob/e3f75b8af2707d64b5dd4c440ae8384ed2f2c386/klog.go#L407
[2] https://go-review.googlesource.com/c/go/+/480215
[3] https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components
=> NO-JIRA: Stop setting logtostderr flag and rely on defaults

pkg/machine/convert.go
Right now we only enforce portSecurity when it's defined
within the Machine's Network field, but the portSecurity
in the Machine's ports field should also be enforced.
This commit fixes the issue by ensuring the value of
PortSecurity is correctly set in the Server port.
=> OCPBUGS-30855: Ensure portSecurity is correctly set in the Port

Makefile, go.mod, pkg/machine/convert.go, pkg/machine/convert_test.go
Drag code out to a separate function, add tests, then start setting the relevant field.
=> OCPBUGS-48288: Stop ignoring port.tags field

pkg/clients/machineservice.go, pkg/clients/utils.go, pkg/machine/actuator.go
In openshift/cloud-credential-operator/pull/780, we have added the ability for `cloud-credential-operator` to consume a CA cert from the root credentials secret and to include in the credentials secrets it provisions.
In openshift/installer/pull/9194, we have modified the Installer to start setting this field where necessary.
Adapt MAPO to allow it to start consuming the CA cert from this place. We maintain fallbacks for the previous locations of the cert for now, but these can be removed in the next release.
This needs wait for the CCO change to be approved before we merge this.
/hold
=> OSASINFRA-3746: Consume CA cert from CCO secret
